# Site settings
title:          Fan Wu
description:    "Home"
# baseurl:        "/tale"
url:            "https://Lucky-Fan.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Fan Wu
  url:          https://Lucky-Fan.github.io
  email:        fwu3@ualberta.ca

# Build settings
markdown: kramdown
kramdown:
    math_engine: katex
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
paginate:       5
permalink:      /:year-:month-:day/:title
paginate_path: "/posts/page:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale