# Site settings
title:          Zhanhong Cheng
description:    "Minimal Jekyll theme for storytellers"
# baseurl:        "/tale"
url:            "https://chengzhanhong.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Zhanhong Cheng
  url:          https://chengzhanhong.github.io
  email:        chengzhanhong@mail.mcgill.ca

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
paginate:       5
permalink:      /posts/:year-:month-:day/:title
paginate_path: "/posts/page:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale